wandb: false
max_seq_length: 512
task: go/autoQA
output_dir: runs/tmp_autoQA
run_name: runs/tmp_autoQA
num_labels: 2
data_dir: data
model_name_or_dir: bert-base-uncased
learning_rate: 5.0e-05
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
do_eval: true
do_predict: true
do_train: true

num_train_epochs: 1.0
evaluation_strategy: yes
eval_steps: 500
load_best_model_at_end: true
save_steps: 1000
max_lines: 100000
logging_first_step: true
logging_steps: 10
fp16: true
label_smoothing: 0.1
