wandb: false
max_seq_length: 256
task: snli_small
output_dir: runs/tmp_snli2
run_name: runs/tmp_snli2
data_dir: data
model_name_or_dir: bert-base-uncased
learning_rate: 5.0e-05
per_device_eval_batch_size: 32
per_device_train_batch_size: 32
do_eval: true
do_predict: true
do_train: true

num_train_epochs: 3.0
evaluation_strategy: yes
eval_steps: 500
load_best_model_at_end: true
save_steps: 1000
max_lines: 100000
logging_first_step: true
logging_steps: 10
fp16: true
label_smoothing: 0.1
