adafactor: false
adam_beta1: 0.9
adam_beta2: 0.999
adam_epsilon: 1.0e-08
cache_dir: null
config_name: null
data_dir: data/cnn_dm
dataloader_drop_last: false
dataloader_num_workers: 0
debug: false
deepspeed: null
disable_tqdm: null
do_eval: true
do_predict: true
do_train: true
eval_accumulation_steps: null
eval_beams: null
eval_steps: null
fp16: true
fp16_backend: auto
fp16_opt_level: O1
freeze_embeds: false
freeze_encoder: false
gradient_accumulation_steps: 1
greater_is_better: null
ignore_data_skip: false
ignore_pad_token_for_loss: true
label_names: null
label_smoothing_factor: 0.0
learning_rate: 3.0e-05
load_best_model_at_end: false
local_rank: -1
logging_dir: runs/Mar21_15-13-34_gpu04.doc.ic.ac.uk
logging_first_step: false
logging_steps: 500
max_grad_norm: 1.0
max_source_length: 1024
max_steps: -1
max_target_length: 128
metric_for_best_model: null
model_name_or_path: sshleifer/bart-tiny-random
n_test: -1
n_train: -1
n_val: 1000
no_cuda: false
num_train_epochs: 3.0
output_dir: runs/tmp_bart
overwrite_output_dir: false
past_index: -1
per_device_eval_batch_size: 8
per_device_train_batch_size: 8
per_gpu_eval_batch_size: null
per_gpu_train_batch_size: null
predict_with_generate: true
prediction_loss_only: false
remove_unused_columns: true
run_name: null
save_steps: 500
save_total_limit: null
seed: 42
sharded_ddp: false
sortish_sampler: false
src_lang: null
task: summarization
test_max_target_length: 142
tgt_lang: null
tokenizer_name: null
tpu_metrics_debug: false
tpu_num_cores: null
val_max_target_length: 142
warmup_steps: 0
weight_decay: 0.0
