wandb: false
wandb_project: test_go
model_name_or_path: facebook/bart-base # {facebook/bart-large-cnn, sshleifer/distilbart-cnn-12-6, facebook/bart-base}
data_dir: data/cnn_dm_small
output_dir: runs/cnn_tmp
learning_rate: 3e-5
fp16: false
do_train: true
do_eval: true
do_predict: true
evaluation_strategy: steps
predict_with_generate: true
n_val: 1000
num_train_epochs: 1
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
val_max_target_length: 142
test_max_target_length: 142
max_source_length: 512
logging_steps: 10
logging_first_step: true
eval_steps: 1000
# overwrite_output_dir: true
