wandb: true
model_name_or_path: facebook/bart-large-cnn # {facebook/bart-large-cnn, sshleifer/bart-tiny-random, facebook/bart-base}
data_dir: data/test_GO
output_dir: runs/test_GO_2
learning_rate: 3e-5
fp16: false
do_train: true
do_eval: true
do_predict: true
evaluation_strategy: steps
predict_with_generate: true
n_val: 1000
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
val_max_target_length: 142
test_max_target_length: 142
max_source_length: 512
logging_steps: 5
logging_first_step: true
eval_steps: 1000
# overwrite_output_dir: true
