data_dir: data/go/section_5
do_eval: true
do_predict: true
do_train: true
eval_steps: 1000
evaluation_strategy: steps
fp16: false
gradient_accumulation_steps: 8
learning_rate: 3e-5
logging_first_step: true
logging_steps: 10
max_source_length: 512
model_name_or_path: sshleifer/bart-tiny-random
n_val: 1000
num_train_epochs: 1
output_dir: runs/section_5/test_GO_01
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
predict_with_generate: true
test_max_target_length: 142
val_max_target_length: 142
wandb: false
wandb_project: test_go
